baseURL = "https://usamav.dev"
title = "Usama Varikkottil"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = "UA-179098654-1"
enableRobotsTXT = true
copyright = "&copy; Copyright 2020, Usama Varikkottil"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

# Configuration Features
[params]
  description = "Looking for a fellow Developer? Poke me. I share myself here. Ideas, Views, Hacks are my favorites. I'm a Social Entrepreneur, Web Developer, Bug Bounty Hunter."      # Your meta description of the site
  header_title = "Usama Varikkottil"                 # Your header title
  header_subtitle = "Entrepreneur | Web Developer | Bug Bounty Hunter" # Your header subtitle
  home_image = "/images/avatar.jpg"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/usamavarikkottil"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/usama-varikkottil/"
  [[params.social]]
    fa_icon = "fab fa-youtube fa-1x"
    href = "https://www.youtube.com/channel/UCPHn0saRG828IyhpzZxJ7qA/videos"
  [[params.social]]
    fa_icon = "fab fa-instagram fa-1x"
    href = "https://www.instagram.com/usama.dev"
#  [[params.social]]
#    fa_icon = "fas fa-at fa-1x"
#    href = "mailto:varikkottilusama@gmail.com"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "http://twitter.com/usama_dev"